name: parsers
version: 1.0.0
authors:
  - Paul Brauner <polux@google.com>
  - Dinesh Ahuja <dev@kabiir.me>
description: >
  Parser combinators for Dart. Parser combinators let you write complex parsers
   by combining smaller, less complex parsers.
homepage: https://github.com/polux/parsers
documentation: http://goo.gl/ZNqdEH
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  # persistent: any
dev_dependencies:
  test: ^1.0.0
